### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ArtanisTheOne** [RitaBot-Project/RitaBot#285]
**Describe the bug**
With peoples' bots sometimes whenever the bot is turned to embed off (database is built, everything checks out) whenever ANY command is run a 404 error is received.

**To Reproduce**
Currently not sure how to reproduce

**Expected behaviour**
Commands should function & no 404 error should be thrown.

**Error Message from Webhook**
```Unhandled Rejection
Caused By:
Error: 404 Not Found
    at /app/node_modules/snekfetch/src/index.js:195:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

![Screenshot_20210329-074526_Discord](https://user-images.githubusercontent.com/52015929/112832091-d504fa00-9062-11eb-816d-ef48a13f143a.jpg)

**Additional context**
Embed on works just fine, but whenever embed is turned off it breaks

**Comment by ArtanisTheOne** [comment]
Fixed, error was because of a missing file from website which was being called
