### ISSUE TITLE
Bug Bounty: DiscordAPIError: Unknown User

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#399]
Though RITA there are many sections of code that require the User ID or Server ID to complete a forwarding operation. 
This Error is caused by a section of code that is unable to locate the user ID to send a message.

This could be for the reason of 
Sending a DM, Warning about a permission issue, Tagging an Owner in a Log message.

As of yet I we have been unable to locate this particular line of, meaning it is still causing issues. 

Once found we will be able to fix and remove this error. This is the last of a bunch of legacy errors we have to Fix. 

This issue will be update with known locations of code **IT IS NOT** caused by, as well as of supporting information 

```md
DiscordAPIError: Unknown User
    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async UserManager.fetch (/app/node_modules/discord.js/src/managers/UserManager.js:67:18)

Error originated from server: undefined
```

**Comment by ZyC0R3** [comment]
Bit of both.

**Comment by ZyC0R3** [comment]
Fixed
