### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'message')

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#532]
```js
29.01 23:05:06 [Bot] DEBUG: No catch for this erorr - Code:undefined
29.01 23:05:06 [Bot] error TypeError: Cannot read properties of null (reading 'message')
29.01 23:05:06 [Bot] at run (/src/core/logger.js:280:16)
29.01 23:05:06 [Bot] at /src/core/send.js:655:16
29.01 23:05:06 [Bot] at runMicrotasks (<anonymous>)
29.01 23:05:06 [Bot] at processTicksAndRejections (node:internal/process/task_queues:96:5) warning
```

**Comment by ZyC0R3** [comment]
This technically is not a bug. I coded that error. This is a valid catch.

**Comment by JShep89** [comment]
maybe add more context to the console output for the catch so a local/self hoster could understand the reason for it
