### ISSUE TITLE
DiscordAPIError: Cannot send messages to this user

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#533]
```js
29.01 23:15:07 [Bot] Unhandled Rejection
29.01 23:15:07 [Bot] Caused By:
29.01 23:15:07 [Bot] DiscordAPIError: Cannot send messages to this user
29.01 23:15:07 [Bot] at RequestHandler.execute (/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
29.01 23:15:07 [Bot] at runMicrotasks (<anonymous>)
29.01 23:15:07 [Bot] at processTicksAndRejections (node:internal/process/task_queues:96:5)
29.01 23:15:07 [Bot] at async RequestHandler.push (/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
29.01 23:15:07 [Bot] Promise At:
29.01 23:15:07 [Bot] undefined 
29.01 23:15:07 [Bot] DEBUG: Unhandled promise rejection: DiscordAPIError: Cannot send messages to this user
29.01 23:15:07 [Bot] at RequestHandler.execute (/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
29.01 23:15:07 [Bot] at runMicrotasks (<anonymous>)
29.01 23:15:07 [Bot] at processTicksAndRejections (node:internal/process/task_queues:96:5)
29.01 23:15:07 [Bot] at async RequestHandler.push (/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
29.01 23:15:07 [Bot] method: 'post',
29.01 23:15:07 [Bot] path: '/channels/929992481049821205/messages',
29.01 23:15:07 [Bot] code: 50007,
29.01 23:15:07 [Bot] httpStatus: 403
29.01 23:15:07 [Bot] }
```

**Comment by ZyC0R3** [comment]
This is the same as #528
